default_platform :ios

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Runs all the tests"
  lane :test do
    danger(github_api_token: ENV["GITHUB_API_TOKEN"], verbose: true)
    #scan(scheme: "Game")
    #xcov(project: "Game.xcodeproj", scheme: "Game", output_directory: "output/xcov_output")
    #danger
    snapshot
  end

  desc "Ad-hoc build"
  lane :adhoc do
    match(type: "adhoc", readonly: is_ci)
    gym(export_method: "ad-hoc", sdk: 'iphoneos')
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    match(type: "appstore")
    gym(export_method: "app-store")
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end
end
