documentation:
    @jazzy \
    	--author Anfield \
        --min-acl internal \
        --no-hide-documentation-coverage \
        --theme fullwidth \
        --output ./docs/jazzy 
    @rm -rf ./build